name: Release Zarf Package

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - flake.*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - upstream
          - registry1
        types:
          - amd64
          - arm64
    outputs:
      git-tag: ${{ steps.describe.outputs.git_describe }}
    steps:
      - name: Sleep for 30 seconds to avoid race condition with arm/amd
        if: ${{ matrix.types == 'arm64' }}
        run: sleep 30s

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get git info
        id: describe
        run: |-
          echo "git_describe=$(git describe --first-parent --tags)" >> "$GITHUB_OUTPUT"

      - name: Install The Latest Release Version of Zarf
        uses: zarf-dev/setup-zarf@10e539efed02f75ec39eb8823e22a5c795f492ae # v1.0.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Registry1
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REG_ONE_USER }}
          password: ${{ secrets.REG_ONE_TOKEN }}

      - name: Package Zarf package
        run: |-
          zarf package create --confirm . --architecture ${{ matrix.types }} --flavor ${{ matrix.flavor }} --set version=${{ steps.describe.outputs.git_describe }}

      - name: Publish Zarf package
        run: |-
          zarf package publish --signing-key env://COSIGN_KEY --signing-key-pass ${{ secrets.COSIGN_PASS }} zarf-*.zst oci://ghcr.io/${{ github.repository_owner }}/zarf
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
